services:
  - type: web
    name: docflow-lite-demo
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    buildFilter:
      ignoredPaths:
        - reports/**
        - uploads_temp/**
        - .tmp_wheels/**
        - __pycache__/**
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
